# Generated by Django 4.2.10 on 2024-07-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_date_alter_todo_sub_title_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sub_title',
            field=models.TextField(default=''),
        ),
    ]
