# Generated by Django 4.2.10 on 2024-07-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sub_title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
