# Generated by Django 4.2.10 on 2024-07-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='sub_title',
            new_name='desc',
        ),
    ]
