# Generated by Django 4.2.10 on 2024-07-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
