# Generated by Django 4.2.10 on 2024-07-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
